### ISSUE TITLE
Add "Add / Update - Shift Timings" - We are able to save the empty value. There is no validation applied for the fields other than "Shift Name ".

### ISSUE THREAD

**Issue by ATSGithub** [ATSGithub/HRMS_2#5]
Add "Add / Update - Shift Timings" - We are able to save the empty value. There is no validation applied for the fields other than "Shift Name ".

**Comment by PrakashHQ** [comment]
Issue resolved.

**Comment by ATSGithub** [comment]
Comments: The validations for all the fields have been applied. However, there are a few issues as below:

1. for minutes 0 to 9 - Add another 0 (Ex: 00, 01, ...09)
2. Upon Editing - Irrespective of the "Weekly Off" selected during "Add" mode, in the "View" mode, it is fetching the 1st value "All Saturdays and All Sundays"

**Comment by Prakashii** [comment]
Issue resolved.

**Comment by ATSGithub** [comment]
All the issues have been resolved. Hence, closing the ticket.
