### ISSUE TITLE
Company Profile - The Company profile page is not displaying the fields "No. of Employees registered and Departments List".

### ISSUE THREAD

**Issue by ATSGithub** [ATSGithub/HRMS_2#6]
Company Profile - The Company profile page is not displaying the fields "No. of Employees registered and Departments List".

**Comment by UmashreeBiradar** [comment]
i resolved all of my issues.

**Comment by UmashreeBiradar** [comment]
i resolved this problem also.

**Comment by ATSGithub** [comment]
ow, we are able to see the the fields "No. of Employees registered and Departments List". However, we are unable to see the complete list of Departments. 

Enable to scroll to view the complete list.

**Comment by UmashreeBiradar** [comment]
i resolved the issue.

**Comment by UmashreeBiradar** [comment]
Now i assigned the role for admin and normal users i solved this issue also.

**Comment by ATSGithub** [comment]
As now we are able to scroll with the normal user credentials. Like-wise, even the Admin user should be able to scroll in the view-mode.

**Comment by UmashreeBiradar** [comment]
i resolved this problem.

**Comment by UmashreeBiradar** [comment]
i resolved all of my issues.

**Comment by ATSGithub** [comment]
The below issues, still exists:

As now we are able to scroll with the normal user credentials. Like-wise, even the Admin user should be able to scroll in the view-mode.

**Comment by UmashreeBiradar** [comment]
i resolved the above issue.

**Comment by ATSGithub** [comment]
The issue still persists in IE (Mocrosoft Edge). However, I'm marking the issue as closed.
